[package]
name = "lundle"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
mlua = { version = "0.9.7", features = ["luajit", "vendored", "macros"] }
glob = "0.3.1"
encoding_rs = "0.8.34"