name: Build Binaries

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v3
      - name: Use Rust toolchain (matrix for target)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.platform.target }}
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.platform.target }}

      - name: Save Binary (name based on target)
        uses: actions/upload-artifact@v3
        with:
          name: lua_obfuscator-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/lundle.exe